/**
 * The MCP tools this server exposes, in registration order.
 *
 * GENERATED FILE - do not edit by hand. The registry is
 * apps/server/cloud/mcp/server.js; run `npm run mcp:tools` after
 * adding, renaming or removing a tool there. `npm run mcp:check` fails when
 * this list and the server disagree.
 */
export const MCP_TOOL_NAMES: readonly string[] = [
  "whoami",
  "get_branding",
  "update_branding",
  "upload_document",
  "analyze_document",
  "create_document",
  "merge_documents",
  "create_upload",
  "complete_upload",
  "register_webhook",
  "list_webhooks",
  "test_webhook",
  "delete_webhook",
  "quick_send",
  "send_document",
  "list_documents",
  "get_document",
  "void_document",
  "replace_signer",
  "resend_to",
  "extend_expiry",
  "set_chain",
  "wait_for",
  "get_audit_trail",
  "verify_document",
  "get_signing_links",
  "send_reminder",
  "list_contacts",
  "add_contact",
  "list_templates",
  "create_document_from_template",
  "get_draft",
  "review_draft",
  "update_draft",
  "set_draft_fields",
  "update_draft_field",
  "remove_draft_fields",
  "ai_layout_draft",
  "preview_page",
  "find_text",
  "detect_fields",
  "place_field_at_text",
  "create_template",
  "save_as_template",
  "delete_template",
  "update_contact",
  "delete_contact",
  "list_folders",
  "create_folder",
  "save_draft_version",
  "list_draft_versions",
  "get_draft_version",
  "restore_draft_version",
  "undo_draft_change",
  "duplicate_document",
  "delete_draft",
  "restore_deleted_document"
];
